apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: prod-clu-grp01
  namespace: default
spec:
  location: westus2
---
apiVersion: containerservice.azure.com/v1api20230201
kind: ManagedCluster
metadata:
  name: asoprodcluswus301
  namespace: default
spec:
  location: westus2
  owner:
    name: prod-clu-grp01
  dnsPrefix: asopc01
  agentPoolProfiles:
    - name: pool1
      count: 1
      vmSize: Standard_DS2_v2
      osType: Linux
      mode: System
    - name: pool2
      count: 3
      vmSize: Standard_DS2_v2
      osType: Linux
      mode: User
  identity:
    type: SystemAssigned
---
kind: Namespace
apiVersion: v1
metadata:
  name: appteam2-ns
  labels:
    name: appteam2-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: appteam2-quota
  namespace: appteam2-ns
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 8Gi