---
kind: Namespace
apiVersion: v1
metadata:
  name: mdwTest
  labels:
    name: mdwTest
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mdwTest-quota
  namespace: mdwTest
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 8Gi
---
kind: Namespace
apiVersion: v1
metadata:
  name: appteam3-app3-ns
  labels:
    name: appteam3-app3-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: appteam3-quota
  namespace: appteam3-app3-ns
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 8Gi
