kind: Namespace
apiVersion: v1
metadata:
  name: appteam1-app1-ns
  labels:
    name: appteam1-app1-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: appteam1-quota
  namespace: appteam1-app1-ns
spec:
  hard:
    requests.cpu: "0.1"
    requests.memory: 500Mb
    limits.cpu: "0.5"
    limits.memory: 1Gb
