kind: Namespace
apiVersion: v1
metadata:
  name: appteam1-app1-ns
  labels:
    name: appteam1-app1-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: appteam1-quota
  namespace: appteam1-app1-ns
spec:
  hard:
    requests.cpu: "4008"
    requests.memory: 500Mi
    limits.cpu: "400m"
    limits.memory: 1Gi
---
kind: Namespace
apiVersion: v1
metadata:
  name: appteam2-app2-ns
  labels:
    name: appteam2-app2-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: appteam2-quota
  namespace: appteam2-app2-ns
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 8Gi
