kind: Namespace
apiVersion: v1
metadata:
  name: appteam1-app1-ns
  labels:
    name: appteam1-app1-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: appteam1-quota
  namespace: appteam1-app1-ns
spec:
  hard:
    requests.cpu: "4008"
    requests.memory: 500Mi
    limits.cpu: "400m"
    limits.memory: 1Gi

