apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: aso-prod-clus-eus2
  namespace: default
spec:
  location: eastus2
---
apiVersion: containerservice.azure.com/v1api20230201
kind: ManagedCluster
metadata:
  name: asoprodcluseus201
  namespace: default
spec:
  location: eastus2
  owner:
    name: aso-prod-clus-eus2
  dnsPrefix: asopc01
  agentPoolProfiles:
    - name: pool1
      count: 1
      vmSize: Standard_DS2_v2
      osType: Linux
      mode: System
  identity:
    type: SystemAssigned
