apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: aso-prod-clusters
  namespace: default
spec:
  location: westus3
---
apiVersion: containerservice.azure.com/v1api20230201
kind: ManagedCluster
metadata:
  name: asoprodcluster01
  namespace: default
spec:
  location: westus3
  owner:
    name: aso-prod-clusters
  dnsPrefix: asopc01
  agentPoolProfiles:
    - name: pool1
      count: 1
      vmSize: Standard_DS2_v2
      osType: Linux
      mode: System
  identity:
    type: SystemAssigned